from __future__ import annotations

from typing import Protocol


class GraphicsDisplay(Protocol):
    @property
    def framebuffer_size(self) -> tuple[int, int]: ...

    @property
    def should_close(self) -> bool: ...

    def make_current(self) -> None: ...

    def poll_events(self) -> None: ...

    def swap_buffers(self) -> None: ...

    def consume_key_events(self) -> tuple[int, ...]: ...

    def close(self) -> None: ...
